### ISSUE TITLE
Old violations aren't removed

### ISSUE THREAD

**Issue by NFarrington** [cmacrae/kove#1]
Currently, violation metrics are never deleted after they are set. This means once a violation is resolved, the metric for it continues to be exported until the exporter is restarted.

Ideally, once a violation ceases to exist, it should then be removed from the Prometheus vector.

**Comment by cmacrae** [comment]
Hey Neil 👋 Good to hear from you!  

Yes, this is an issue I've been meaning to address.  
I've been working on some other functionality recently which I'll release soon - I'll implement a fix for this in that release also 👍

**Comment by cmacrae** [comment]
Just a heads up: a fix for this wasn't provided in v1.0.0, but I promise it's coming in a patch release shortly! Need to do some more testing

**Comment by cmacrae** [comment]
Alright, a fix for this is up on the `refactor/watch_model` branch 🚀   
As per the note in the `master` README, I'm doing quite a bit of refactoring at the moment: a release will be coming soon, once I've got it in the shape I want.

Just as a heads up @NFarrington, there'll be breaking changes and some tag shuffling (metrics are being renamed to `policy_violation`, and the prematurely-assigned `1.0.0` tag will be regressed - Helm chart will update of course).  
I'll shout here about updating once it's ready :)

**Comment by NFarrington** [comment]
Awesome, thanks 😄
